### ISSUE TITLE
whata hell

### ISSUE THREAD

**Issue by burialstance** [13-05/hidden-disc-docs#1]
mid = str(ch(CHARS2) + ch(CHARS2) + ch(CHARS2) + ch(CHARS2) + ch(CHARS2) + ch(CHARS2))

**Comment by 13-05** [comment]
what?

**Comment by 13-05** [comment]
oh yeah i forgor i suck at python

dont try token crackers, i wrote a warning that it takes like 4 years with a super low chance to get one even after you wait that long

**Comment by 13-05** [comment]
closing this lmfao
