### ISSUE TITLE
Friendinvite snippet doesn't send a link in logs

### ISSUE THREAD

**Issue by sneazy-ibo** [13-05/hidden-disc-docs#2]
I pasted the [script](https://github.com/13-05/hidden-disc-docs#js-snippet-for-creating-friend-invites) in my console but it gives me only a `undefined` message. Am I doing smth wrong?

**Comment by 13-05** [comment]
did you paste the whole thing?
```js
var mod;window.webpackChunkdiscord_app.push([[Math.random()],{},(e)=>{mod=mod||Object.values(e.c).find(m=>m?.exports?.default&&m.exports.default["createFriendInvite"])}]);

console.log(`Friend invite: https://discord.gg/${(await mod.exports.default.createFriendInvite()).code}`);
```
it should give you the friend invite *and* an undefined message, undefined being the return value and the friend invite being the log (below)
![image](https://user-images.githubusercontent.com/64506392/168444539-3e75abeb-b5db-4eed-9b0e-a9973e6794d1.png)
make sure `info` is selected on the log filters for chrome, as that may be why you can't see anything
![image](https://user-images.githubusercontent.com/64506392/168444558-eb1ee1db-f255-4576-ac19-88c2e2715a52.png)

**Comment by 13-05** [comment]
updated [the snippet](https://github.com/13-05/hidden-disc-docs#js-snippet-for-creating-friend-invites), try it now and lmk if it still doesnt work

reach out to me on discord at ./go_touch_grass.exe#3057 if you find that easier to talk through than issues

**Comment by sneazy-ibo** [comment]
> make sure `info` is selected on the log filters for chrome, as that may be why you can't see anything ![image](https://user-images.githubusercontent.com/64506392/168444558-eb1ee1db-f255-4576-ac19-88c2e2715a52.png)

Ah I see, I disabled everything bc it kinda annoys me after opening dev tools everytime. Tysm for the hint I had it disabled that's why I didn't see the link.

**Comment by 13-05** [comment]
👍
